name: Algorithm release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x, 17.x, 18.x]

    steps:
      - name: Checkout nodejs
      - uses: actions/checkout@v2

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif

      - name: Check cache
        uses: actions/cache@v3.0.2

      - name: Run CI process
        run: npm ci

      - name: Start installation process
        run: npm i

      - name: Check Formatter rules
        run: npm run fomatter:check

      - name: Check Linter rules
        run: npm run linter:check

      - name: Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2.0.6

      - name: Run Unit tests
        run: npm run test

      - name: Build a project
        run: npm run build
